/**
 * 图标库 type 列表（与 icon 目录 SVG 文件名一致，不含 .svg）
 * 与 iconfont 的 class 后缀对应：icon-{type}
 */
export const iconTypes: string[] = [
  'Info', 'activity', 'activity-filled', 'add', 'add-circle', 'add-circle-filled', 'add-rectangle',
  'address-book', 'address-book-filled', 'adjustment', 'adjustment-filled', 'airplay-wave', 'airplay-wave-filled',
  'alarm', 'alarm-filled', 'align-bottom', 'align-top', 'align-vertical', 'app', 'app-filled',
  'arrow-down', 'arrow-left', 'arrow-left-down', 'arrow-left-up', 'arrow-right', 'arrow-right-down', 'arrow-right-up', 'arrow-up',
  'arrow-triangle-down', 'arrow-triangle-down-filled', 'arrow-triangle-up', 'arrow-triangle-up-filled',
  'attach', 'barcode-1', 'base-station', 'bill', 'bill-filled', 'bluetooth',
  'book-open', 'book-open-filled', 'book-unknown', 'book-unknown-filled', 'bookmark', 'bookmark-filled',
  'browse', 'browse-filled', 'browse-off', 'browse-off-filled', 'bulletpoint',
  'calendar-1', 'calendar-1-filled', 'calendar-2', 'calendar-2-filled',
  'call', 'call-1', 'call-1-filled', 'call-filled', 'call-off', 'call-off-filled',
  'camera', 'camera-filled', 'caret-down-small', 'caret-left-small', 'caret-right-small', 'caret-up-small',
  'cart', 'cart-filled', 'catalog', 'catalog-filled', 'certificate-1', 'certificate-1-filled',
  'chart', 'chart-analytics', 'chart-combo', 'chart-combo-filled', 'chart-filled', 'chart-line-data-1', 'chart-pie', 'chart-pie-filled',
  'chat-double', 'chat-double-filled', 'chat-filled', 'chat-message',
  'check', 'check-circle', 'check-circle-filled',
  'chevron-down', 'chevron-down-circle', 'chevron-down-circle-filled', 'chevron-down-double', 'chevron-down-rectangle',
  'chevron-left', 'chevron-left-circle', 'chevron-left-circle-filled', 'chevron-left-rectangle', 'a-chevron-leftdouble',
  'chevron-right', 'chevron-right-circle', 'chevron-right-circle-filled', 'chevron-right-rectangle', 'a-chevron-rightdouble',
  'chevron-up', 'chevron-up-circle', 'chevron-up-circle-filled', 'chevron-up-double', 'chevron-up-rectangle',
  'clear', 'clear-filled', 'clear-formatting', 'clear-formatting-filled', 'close', 'close-circle', 'close-circle-filled',
  'cloud-download', 'cloud-upload', 'compass', 'compass-filled', 'control-platform', 'control-platform-filled',
  'copy', 'course', 'course-filled', 'cpu', 'cpu-filled', 'creditcard', 'creditcard-filled', 'data-filled',
  'delete', 'delete-filled', 'desktop', 'desktop-filled', 'device', 'device-filled', 'download',
  'edit', 'edit-filled', 'ellipsis', 'error', 'error-circle', 'error-circle-filled', 'error-triangle', 'error-triangle-filled',
  'expand-horizontal', 'expand-vertical',
  'file-1', 'file-1-filled', 'file-copy', 'file-copy-filled',
  'filter', 'filter-2', 'filter-2-filled', 'filter-filled', 'flag', 'flag-filled',
  'folder', 'folder-filled', 'folder-open-1', 'folder-open-1-filled', 'fork', 'fork-filled',
  'form', 'form-filled', 'format-vertical-align-center', 'format-vertical-align-left', 'format-vertical-align-right',
  'fullscreen', 'fullscreen-1', 'fullscreen-exit', 'fullscreen-exit-1',
  'gift', 'gift-filled', 'grid-add', 'grid-add-filled', 'grid-view', 'grid-view-filled',
  'heart', 'heart-filled', 'help', 'help-circle', 'help-circle-filled', 'history',
  'home', 'home-filled', 'hotspot-wave', 'hotspot-wave-filled',
  'image', 'image-1', 'image-1-filled', 'image-filled', 'indent-left', 'indent-right',
  'info-circle', 'info-circle-filled', 'internet', 'jump',
  'keyboard', 'keyboard-filled', 'lightbulb', 'lightbulb-filled', 'line-height', 'link', 'link-unlink', 'load',
  'location', 'location-filled', 'lock-off', 'lock-off-filled', 'lock-on', 'lock-on-filled', 'login', 'logout',
  'mail', 'mail-filled', 'map', 'map-filled', 'map-information-2', 'map-information-2-filled', 'map-ruler', 'map-ruler-filled',
  'menu-application', 'microphone-1', 'microphone-1-filled', 'minus-circle', 'minus-circle-filled', 'minus-rectangle',
  'mobile', 'mobile-filled', 'mode-dark', 'mode-dark-filled', 'mode-light', 'mode-light-filled', 'more', 'mouse', 'mouse-filled', 'move', 'move-1',
  'no-result', 'no-result-filled', 'notification', 'notification-filled', 'object-storage', 'a-order-adjustmentcolumn', 'order-ascending', 'order-descending',
  'palette', 'palette-filled', 'pause-circle', 'pause-circle-filled', 'pin', 'pin-filled',
  'play-circle', 'play-circle-filled', 'print', 'print-filled', 'qrcode', 'refresh',
  'remote-wave', 'remote-wave-filled', 'remove', 'rocket', 'rocket-filled', 'rollback', 'rollfront',
  'save', 'save-filled', 'scan', 'search', 'search-filled', 'secured', 'secured-filled', 'send', 'send-filled',
  'sensors', 'sensors-1', 'server', 'service', 'service-filled', 'setting', 'setting-filled', 'share', 'share-filled',
  'shield-error', 'shield-error-filled', 'shop', 'shop-filled', 'shrink-horizontal', 'sonic',
  'sound-low', 'sound-low-filled', 'sound-mute-1', 'sound-mute-1-filled', 'stop-circle', 'stop-circle-filled',
  'store', 'store-filled', 'swap', 'swap-left', 'swap-right', 'system-application', 'system-application-filled',
  'tag', 'tag-filled', 'task', 'task-filled', 'textformat-bold', 'textformat-color', 'textformat-italic', 'textformat-strikethrough', 'textformat-underline',
  'thumb-down', 'thumb-down-filled', 'thumb-up', 'thumb-up-filled', 'ticket', 'ticket-filled', 'time', 'time-filled', 'tips', 'tips-filled', 'translate',
  'tree-round-dot', 'tree-round-dot-filled', 'tree-round-dot-vertical', 'tree-round-dot-vertical-filled', 'unfold-less', 'unfold-more',
  'upload', 'usb', 'usb-filled', 'user', 'user-add', 'user-add-filled', 'user-checked', 'user-checked-filled', 'user-filled',
  'user-list', 'user-list-filled', 'user-setting', 'user-setting-filled', 'user-transmit', 'user-transmit-filled',
  'verify', 'verify-filled', 'video-camera', 'video-camera-filled', 'view-in-ar', 'view-list',
  'wallet', 'wallet-filled', 'wifi', 'wifi-1-filled', 'wifi-no', 'wifi-no-filled', 'wifi-off', 'wifi-off-1-filled',
  'zoom-in', 'zoom-in-filled', 'zoom-out', 'zoom-out-filled',
];
