import React from 'react';
import { navGroups } from '../navConfig';
import Overview from './Overview';
import ButtonDemo from './ButtonDemo';
import FloatButtonDemo from './FloatButtonDemo';
import IconDemo from './IconDemo';
import TypographyDemo from './TypographyDemo';
import DividerDemo from './DividerDemo';
import FlexDemo from './FlexDemo';
import GridDemo from './GridDemo';
import LayoutDemo from './LayoutDemo';
import SpaceDemo from './SpaceDemo';
import SplitterDemo from './SplitterDemo';
import AnchorDemo from './AnchorDemo';
import BreadcrumbDemo from './BreadcrumbDemo';
import DropdownDemo from './DropdownDemo';
import MenuDemo from './MenuDemo';
import PaginationDemo from './PaginationDemo';
import StepsDemo from './StepsDemo';
import TabsDemo from './TabsDemo';
import AutoCompleteDemo from './AutoCompleteDemo';
import CascaderDemo from './CascaderDemo';
import CheckboxDemo from './CheckboxDemo';
import ColorPickerDemo from './ColorPickerDemo';
import DatePickerDemo from './DatePickerDemo';
import FormDemo from './FormDemo';
import InputDemo from './InputDemo';
import InputNumberDemo from './InputNumberDemo';
import MentionsDemo from './MentionsDemo';
import RadioDemo from './RadioDemo';
import RateDemo from './RateDemo';
import SelectDemo from './SelectDemo';
import SliderDemo from './SliderDemo';
import SwitchDemo from './SwitchDemo';
import TimePickerDemo from './TimePickerDemo';
import TransferDemo from './TransferDemo';
import TreeSelectDemo from './TreeSelectDemo';
import UploadDemo from './UploadDemo';
import AvatarDemo from './AvatarDemo';
import AffixDemo from './AffixDemo';
import BadgeDemo from './BadgeDemo';
import CalendarDemo from './CalendarDemo';
import CardDemo from './CardDemo';
import CarouselDemo from './CarouselDemo';
import CollapseDemo from './CollapseDemo';
import DescriptionsDemo from './DescriptionsDemo';
import EmptyStateDemo from './EmptyStateDemo';
import ImageDemo from './ImageDemo';
import ListDemo from './ListDemo';
import PopoverDemo from './PopoverDemo';
import QRCodeDemo from './QRCodeDemo';
import SegmentedDemo from './SegmentedDemo';
import StatisticDemo from './StatisticDemo';
import TableDemo from './TableDemo';
import TagDemo from './TagDemo';
import TimelineDemo from './TimelineDemo';
import TooltipDemo from './TooltipDemo';
import TourDemo from './TourDemo';
import TreeDemo from './TreeDemo';
import AlertDemo from './AlertDemo';
import DrawerDemo from './DrawerDemo';
import ModalDemo from './ModalDemo';
import MessageDemo from './MessageDemo';
import NotificationDemo from './NotificationDemo';
import PopconfirmDemo from './PopconfirmDemo';
import ProgressDemo from './ProgressDemo';
import ResultDemo from './ResultDemo';
import SkeletonDemo from './SkeletonDemo';
import SpinDemo from './SpinDemo';
import ConfigProviderDemo from './ConfigProviderDemo';
import BizMenuCaseDemo from './BizMenuCaseDemo';
import FilterAreaDemo from './FilterAreaDemo';
import SwitchAreaDemo from './SwitchAreaDemo';
import OperationBarDemo from './OperationBarDemo';
import BizTableDemo from './BizTableDemo';
import VcellTableDemo from './VcellTableDemo';
import EmptyDemo from './EmptyDemo';
import BizListPageCompositionDemo from './BizListPageCompositionDemo';

const keyToLabel: Record<string, string> = {};
navGroups.forEach((g) => g.items.forEach((it) => { keyToLabel[it.key] = it.label; }));

export function getComponentLabel(key: string): string {
  return keyToLabel[key] ?? key;
}

export function DemoContent({ selectedKey }: { selectedKey: string }) {
  if (selectedKey === 'overview') return <Overview />;
  if (selectedKey === 'affix') return <AffixDemo />;
  if (selectedKey === 'button') return <ButtonDemo />;
  if (selectedKey === 'float-button') return <FloatButtonDemo />;
  if (selectedKey === 'icon') return <IconDemo />;
  if (selectedKey === 'typography') return <TypographyDemo />;
  if (selectedKey === 'divider') return <DividerDemo />;
  if (selectedKey === 'flex') return <FlexDemo />;
  if (selectedKey === 'grid') return <GridDemo />;
  if (selectedKey === 'layout') return <LayoutDemo />;
  if (selectedKey === 'space') return <SpaceDemo />;
  if (selectedKey === 'splitter') return <SplitterDemo />;
  if (selectedKey === 'anchor') return <AnchorDemo />;
  if (selectedKey === 'breadcrumb') return <BreadcrumbDemo />;
  if (selectedKey === 'dropdown') return <DropdownDemo />;
  if (selectedKey === 'menu') return <MenuDemo />;
  if (selectedKey === 'pagination') return <PaginationDemo />;
  if (selectedKey === 'steps') return <StepsDemo />;
  if (selectedKey === 'tabs') return <TabsDemo />;
  if (selectedKey === 'auto-complete') return <AutoCompleteDemo />;
  if (selectedKey === 'cascader') return <CascaderDemo />;
  if (selectedKey === 'checkbox') return <CheckboxDemo />;
  if (selectedKey === 'color-picker') return <ColorPickerDemo />;
  if (selectedKey === 'date-picker') return <DatePickerDemo />;
  if (selectedKey === 'form') return <FormDemo />;
  if (selectedKey === 'input') return <InputDemo />;
  if (selectedKey === 'input-number') return <InputNumberDemo />;
  if (selectedKey === 'mentions') return <MentionsDemo />;
  if (selectedKey === 'radio') return <RadioDemo />;
  if (selectedKey === 'rate') return <RateDemo />;
  if (selectedKey === 'select') return <SelectDemo />;
  if (selectedKey === 'slider') return <SliderDemo />;
  if (selectedKey === 'switch') return <SwitchDemo />;
  if (selectedKey === 'time-picker') return <TimePickerDemo />;
  if (selectedKey === 'transfer') return <TransferDemo />;
  if (selectedKey === 'tree-select') return <TreeSelectDemo />;
  if (selectedKey === 'upload') return <UploadDemo />;
  if (selectedKey === 'avatar') return <AvatarDemo />;
  if (selectedKey === 'badge') return <BadgeDemo />;
  if (selectedKey === 'calendar') return <CalendarDemo />;
  if (selectedKey === 'card') return <CardDemo />;
  if (selectedKey === 'carousel') return <CarouselDemo />;
  if (selectedKey === 'collapse') return <CollapseDemo />;
  if (selectedKey === 'descriptions') return <DescriptionsDemo />;
  if (selectedKey === 'empty') return <EmptyStateDemo />;
  if (selectedKey === 'image') return <ImageDemo />;
  if (selectedKey === 'list') return <ListDemo />;
  if (selectedKey === 'popover') return <PopoverDemo />;
  if (selectedKey === 'qrcode') return <QRCodeDemo />;
  if (selectedKey === 'segmented') return <SegmentedDemo />;
  if (selectedKey === 'statistic') return <StatisticDemo />;
  if (selectedKey === 'table') return <TableDemo />;
  if (selectedKey === 'tag') return <TagDemo />;
  if (selectedKey === 'timeline') return <TimelineDemo />;
  if (selectedKey === 'tooltip') return <TooltipDemo />;
  if (selectedKey === 'tour') return <TourDemo />;
  if (selectedKey === 'tree') return <TreeDemo />;
  if (selectedKey === 'alert') return <AlertDemo />;
  if (selectedKey === 'drawer') return <DrawerDemo />;
  if (selectedKey === 'message') return <MessageDemo />;
  if (selectedKey === 'modal') return <ModalDemo />;
  if (selectedKey === 'notification') return <NotificationDemo />;
  if (selectedKey === 'popconfirm') return <PopconfirmDemo />;
  if (selectedKey === 'progress') return <ProgressDemo />;
  if (selectedKey === 'result') return <ResultDemo />;
  if (selectedKey === 'skeleton') return <SkeletonDemo />;
  if (selectedKey === 'spin') return <SpinDemo />;
  if (selectedKey === 'config-provider') return <ConfigProviderDemo />;
  if (selectedKey === 'dispatch-sider-nav') return <BizMenuCaseDemo />;
  if (selectedKey === 'dispatch-filter-area') return <FilterAreaDemo />;
  if (selectedKey === 'switch-area') return <SwitchAreaDemo />;
  if (selectedKey === 'operation-bar') return <OperationBarDemo />;
  if (selectedKey === 'biz-table') return <BizTableDemo />;
  if (selectedKey === 'vcell-table') return <VcellTableDemo />;
  if (selectedKey === 'list-page-shell') return <BizListPageCompositionDemo />;
  return <EmptyDemo componentName={getComponentLabel(selectedKey)} />;
}
